# Generated by Django 3.0.8 on 2020-07-23 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_emp_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='pno',
            new_name='phno',
        ),
    ]
