# Generated by Django 3.0.8 on 2020-07-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200723_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='phno',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
