# Generated by Django 3.0.8 on 2020-07-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20200723_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='dept',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='phno',
            field=models.IntegerField(null=True),
        ),
    ]
