# Generated by Django 3.0.8 on 2020-07-25 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20200724_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='dept',
        ),
    ]
