# Generated by Django 3.0.8 on 2020-07-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_emp_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='empid',
            field=models.IntegerField(null=True),
        ),
    ]
