# Generated by Django 3.0.8 on 2020-07-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_emp_empid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='id',
        ),
        migrations.AlterField(
            model_name='emp',
            name='empid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
